### ISSUE TITLE
Main menu Buttons

### ISSUE THREAD

**Issue by arraypan** [Deanout/project337#2]
Help back button doesn't work, Setting back button doesn't work and Quit doesn't work 
<img width="1440" alt="screen shot 2016-11-07 at 9 40 26 pm" src="https://cloud.githubusercontent.com/assets/8212014/20084814/d5bc1476-a532-11e6-8992-ac834d78dcc6.png">

**Comment by Deanout** [comment]
Have you tried turning it off and back on again?

**Comment by Deanout** [comment]
With the addition of the newest main menu, this issue has been resolved.
